spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sgp?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=False;&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password: "16B0FE830Nm."
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: MYSQL
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    enabled: true
  mail:
    protocol: smtp
    host: smtp@gmail.com
    username: hedichaker.sgp@gmail.com
    password: sgp12345
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    #    prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
    #    prefix: ${project.basedir}/src/main/resources/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
    servlet:
      content-type: text/html
  devtools:
    livereload:
      enabled: true
    add-properties: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
      location: ${java.io.tmpdir}
  session:
    store-type: none
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  client:
    registration:
      azure:
        client-id: ${CLIENT_ID}
        client-secret:  ${CLIENT_SECRET}
        authorization-grant-type: authorization_code
        redirect-uri: https://myapp.azurewebsites.net/home
        scope: openid email profile
        client-authentication-method: post
      #    static-locations: ${project.basedir}/src/main/resources/static/

#We can use the httpOnly and secure flags to secure our session cookie:
#
#httpOnly: if true then browser script won't be able to access the cookie
#secure: if true then the cookie will be sent only over HTTPS connection
server:
  servlet:
    session:
      cookie:
        http-only: true
        #        secure: true
        maxAge: 86400
# 1 days = 1 * 24 * 60 * 60

logging:
  level:
    org:
      springframework:
        security: DEBUG